#!/usr/bin/env python3
"""Validate the authored joke bank and compile immutable C++ flash data."""
import argparse
import collections
import json
from pathlib import Path
import re
import zlib

ROOT = Path(__file__).resolve().parent.parent
MOODS = ('neutral', 'hungry', 'full', 'bored', 'happy', 'tired', 'rested', 'sleeping')
TOPICS = ('work', 'bureaucracy', 'technology', 'money', 'social', 'language',
          'science', 'nature', 'food', 'sleep', 'sloth', 'absurd')
SUPPORTED = re.compile(r"[A-Za-z0-9 .,!?:'/%-]+\Z")


def wrapped(text):
    lines = []
    for word in text.split():
        if not lines or len(lines[-1]) + 1 + len(word) > 32:
            lines.append(word)
        else:
            lines[-1] += ' ' + word
    return lines


def validate(entries, minimum=2048):
    if not minimum <= len(entries) <= 4096:
        raise ValueError(f'Expected {minimum}..4096 jokes, found {len(entries)}')
    ids, texts = set(), set()
    for entry in entries:
        if set(entry) != {'id', 'text', 'mood', 'topic', 'family'}:
            raise ValueError(f'Unexpected fields: {entry.get("id", "missing ID")}')
        if not all(isinstance(value, str) for value in entry.values()):
            raise ValueError('All joke fields must be strings')
        ident, text = entry['id'], entry['text']
        if not re.fullmatch(r'[gp][0-9]{4}', ident) or ident in ids:
            raise ValueError(f'Invalid or duplicate ID: {ident}')
        ids.add(ident)
        normalized = ' '.join(re.findall(r'[a-z0-9]+', text.lower()))
        if normalized in texts:
            raise ValueError(f'Duplicate joke: {ident}: {text}')
        texts.add(normalized)
        if not text or text != ' '.join(text.split()) or len(text) > 132 or not SUPPORTED.fullmatch(text):
            raise ValueError(f'Unsupported or overlong text: {ident}: {text}')
        if max(map(len, text.split())) > 20 or len(wrapped(text)) > 7:
            raise ValueError(f'Joke will not fit speech card: {ident}')
        if entry['mood'] not in MOODS or entry['topic'] not in TOPICS:
            raise ValueError(f'Unknown mood/topic: {ident}')
        if not re.fullmatch(r'[a-z0-9][a-z0-9-]{0,79}', entry['family']):
            raise ValueError(f'Invalid family: {ident}')
    return sorted(entries, key=lambda item: item['id'])


def merge_families(entries, aliases):
    """Unify reviewed cross-author premises, retaining each local family too."""
    by_id = {entry['id']: entry for entry in entries}
    parent = {entry['family']: entry['family'] for entry in entries}

    def root(name):
        while parent[name] != name:
            name = parent[name]
        return name

    for name, ids in sorted(aliases.items()):
        if not re.fullmatch(r'[a-z0-9-]+', name) or not isinstance(ids, list) or len(ids) < 2:
            raise ValueError(f'Invalid shared premise: {name}')
        if len(set(ids)) != len(ids) or any(ident not in by_id for ident in ids):
            raise ValueError(f'Unknown or duplicate ID in shared premise: {name}')
        roots = sorted({root(by_id[ident]['family']) for ident in ids})
        for family in roots:
            parent[family] = roots[0]
    return [dict(entry, family=root(entry['family'])) for entry in entries]


def generate(entries, aliases=None):
    entries = validate(entries)
    entries = merge_families(entries, aliases or {})
    canonical = json.dumps(entries, ensure_ascii=True, sort_keys=True, separators=(',', ':')).encode()
    version = zlib.crc32(canonical)
    families = {name: index for index, name in enumerate(sorted({e['family'] for e in entries}))}
    lines = ['// Generated by scripts/generate_humor.py from content/humor/*.jsonl.',
             '// Original authored lines; keep changes in the JSONL sources.',
             '#include "pet_humor.h"', '', 'namespace sloth {', 'namespace {',
             'const Joke kJokes[] = {']
    for entry in entries:
        text = json.dumps(entry['text'], ensure_ascii=True)
        lines.append(f'  {{{text}, {families[entry["family"]]}, {TOPICS.index(entry["topic"])}, '
                     f'HumorMood::{entry["mood"].title()}}}, // {entry["id"]}')
    lines.extend(['};', 'const Joke kEmptyJoke = {"", 0, 0, HumorMood::Neutral};',
                  '} // namespace', '', 'size_t jokeCount() { return sizeof(kJokes) / sizeof(kJokes[0]); }',
                  'const Joke& jokeAt(size_t index) { return index < jokeCount() ? kJokes[index] : kEmptyJoke; }',
                  f'uint32_t humorBankVersion() {{ return 0x{version:08x}u; }}',
                  '} // namespace sloth', ''])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if committed C++ data is stale')
    args = parser.parse_args()
    entries = []
    for path in sorted((ROOT / 'content/humor').glob('*.jsonl')):
        for line in path.read_text().splitlines():
            if line.strip():
                entries.append(json.loads(line))
    aliases = json.loads((ROOT / 'content/humor/shared_families.json').read_text())
    output = generate(entries, aliases)
    target = ROOT / 'firmware/sloth_pet/humor_bank.cpp'
    if args.check:
        if not target.exists() or target.read_text() != output:
            raise SystemExit('Generated humor bank is stale; run scripts/generate_humor.py')
    else:
        target.write_text(output)
    merged = merge_families(entries, aliases)
    print(f'{len(entries)} distinct jokes, {len({e["family"] for e in merged})} premises, '
          f'{sum(len(e["text"]) + 1 for e in entries)} text bytes')
    for field in ('mood', 'topic'):
        print(field + ': ' + str(dict(sorted(collections.Counter(e[field] for e in entries).items()))))


if __name__ == '__main__':
    main()
